image: maven:latest

stages:
  - pack

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  VERSION: 3.96.31

pack:
  stage: pack
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - /builds/mcib3d/mcib3d-core/target/mcib3d-core-$VERSION.jar
    expire_in: 1 week
