/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tango.gui.util;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author jean
 */
public class DeleteSlicePanel extends javax.swing.JPanel implements ChangeListener {

    /**
     * Creates new form DeleteSlicePanel
     */
    public DeleteSlicePanel(int nSlices) {
        initComponents();
        this.sliderStart.setMaximum(nSlices);
        this.sliderStop.setMaximum(nSlices);
        this.sliderStart.setMinimum(1);
        this.sliderStop.setMinimum(1);
        this.sliderStart.setValue(1);
        this.sliderStop.setValue(nSlices);
        sliderStart.setMinorTickSpacing(1);
        sliderStart.setMajorTickSpacing(10);
        sliderStart.setPaintTicks(true);
        sliderStart.setPaintLabels(true);
        sliderStop.setMinorTickSpacing(1);
        sliderStop.setMajorTickSpacing(10);
        sliderStop.setPaintTicks(true);
        sliderStop.setPaintLabels(true);
        sliderStart.addChangeListener(this);
        sliderStop.addChangeListener(this);
        this.startSliceLabel.setText(""+1);
        this.stopSliceLabel.setText(""+nSlices);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sliderStart = new javax.swing.JSlider();
        sliderStop = new javax.swing.JSlider();
        buttonCancel = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();
        startSliceLabel = new javax.swing.JLabel();
        stopSliceLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Keep Only Slices:"));

        jLabel1.setText("Start Slice: ");

        jLabel2.setText("Stop Slice:");

        buttonCancel.setText("Cancel");

        buttonOk.setText("OK");

        startSliceLabel.setText("1000");

        stopSliceLabel.setText("1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startSliceLabel)
                    .addComponent(stopSliceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sliderStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOk)
                            .addComponent(buttonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(startSliceLabel)
                        .addGap(35, 35, 35)
                        .addComponent(stopSliceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton buttonCancel;
    protected javax.swing.JButton buttonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JSlider sliderStart;
    protected javax.swing.JSlider sliderStop;
    private javax.swing.JLabel startSliceLabel;
    private javax.swing.JLabel stopSliceLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e) {
        if (e.getSource()==sliderStart) {
            this.startSliceLabel.setText(""+sliderStart.getValue());
        }else if (e.getSource()==sliderStop) {
            this.stopSliceLabel.setText(""+sliderStop.getValue());
        }
    }
}
