/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tango.gui.util;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import tango.gui.Core;

/**
 *
 * @author jollion
 */
public class OverrideXPPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverrideXPPanel
     */
    DefaultMutableTreeNode treeNode;
    DefaultTreeModel tm;
    public OverrideXPPanel() {
        treeNode = createTree();
        tm = new DefaultTreeModel(treeNode);
        initComponents();
         
    }
    
    protected DefaultMutableTreeNode createTree() {
        DefaultMutableTreeNode top = new DefaultMutableTreeNode(Core.mongoConnector.getUserName());
        DefaultMutableTreeNode project = null;
        DefaultMutableTreeNode xp = null;
        for (String p : Core.mongoConnector.getProjects()) {
            project = new DefaultMutableTreeNode(p);
            top.add(project);
            for (String x : Core.mongoConnector.getExperiments(p)) {
                xp = new DefaultMutableTreeNode(x);
                project.add(xp);
            }
        }
        return top;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        cbShowOnly = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cbChannelFiles = new javax.swing.JCheckBox();
        cbStructures = new javax.swing.JCheckBox();
        cbvirtStructures = new javax.swing.JCheckBox();
        cbMeas = new javax.swing.JCheckBox();
        cbSamplers = new javax.swing.JCheckBox();
        buttonCancel = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();

        jTree.setModel(tm);
        jScrollPane1.setViewportView(jTree);

        cbShowOnly.setText("Display Only experiments with same number of structure");
        cbShowOnly.setEnabled(false);
        cbShowOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowOnlyActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select parameter to override:"));

        cbChannelFiles.setText("Channel Files");

        cbStructures.setText("Structures");
        cbStructures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStructuresActionPerformed(evt);
            }
        });

        cbvirtStructures.setText("Virtual Structures");

        cbMeas.setSelected(true);
        cbMeas.setText("Measurements");

        cbSamplers.setSelected(true);
        cbSamplers.setText("Samplers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbChannelFiles)
                    .addComponent(cbStructures)
                    .addComponent(cbvirtStructures)
                    .addComponent(cbMeas)
                    .addComponent(cbSamplers))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbChannelFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStructures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbvirtStructures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMeas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSamplers)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        buttonCancel.setText("Cancel");

        buttonOk.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbShowOnly)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(cbShowOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOk)
                            .addComponent(buttonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowOnlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowOnlyActionPerformed

    private void cbStructuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStructuresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStructuresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton buttonCancel;
    protected javax.swing.JButton buttonOk;
    protected javax.swing.JCheckBox cbChannelFiles;
    protected javax.swing.JCheckBox cbMeas;
    protected javax.swing.JCheckBox cbSamplers;
    private javax.swing.JCheckBox cbShowOnly;
    protected javax.swing.JCheckBox cbStructures;
    protected javax.swing.JCheckBox cbvirtStructures;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
